/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package redes;

import javax.swing.DefaultListModel;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JList;
import javax.swing.JOptionPane;

/**
 *
 * @author Cesar
 */
public class Ventana extends javax.swing.JFrame {

    /**
     * Creates new form Ventana
     *
     * @param titulo
     */
    public Ventana(String titulo) {
        super(titulo);
        initComponents();
        ListaProductos.setModel(new DefaultListModel());
        ListaProductosCasa.setModel(new DefaultListModel());
        inventario = new Inventario();
        actualizarPrecio("Producto 1");
        actualizarPrecio("Producto 2");
        actualizarPrecio("Producto 3");
        actualizarPrecio("Producto 4");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jButton16 = new javax.swing.JButton();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jPanel10 = new javax.swing.JPanel();
        Producto_1 = new javax.swing.JButton();
        Producto_3 = new javax.swing.JButton();
        Producto_4 = new javax.swing.JButton();
        Producto_2 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        jPanel8 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        ListaProductos = new javax.swing.JList<>();
        Comprar = new javax.swing.JButton();
        jPanel9 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jPanel12 = new javax.swing.JPanel();
        jPanel13 = new javax.swing.JPanel();
        jPanel14 = new javax.swing.JPanel();
        jPanel15 = new javax.swing.JPanel();
        ProductoCasa1 = new javax.swing.JButton();
        ProductoCasa3 = new javax.swing.JButton();
        ProductoCasa4 = new javax.swing.JButton();
        ProductoCasa2 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jPanel16 = new javax.swing.JPanel();
        jPanel17 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        ListaProductosCasa = new javax.swing.JList<>();
        Comprar1 = new javax.swing.JButton();
        jPanel18 = new javax.swing.JPanel();
        jPanel19 = new javax.swing.JPanel();
        jButton8 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jButton10 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();

        jButton16.setText("jButton16");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new java.awt.GridBagLayout());

        jPanel5.setLayout(new java.awt.GridBagLayout());

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new java.awt.GridBagLayout());

        jPanel10.setBackground(new java.awt.Color(255, 255, 255));
        jPanel10.setLayout(new java.awt.GridBagLayout());

        Producto_1.setText("Producto 1");
        Producto_1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Producto_1MouseClicked(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 0.1;
        gridBagConstraints.weighty = 0.1;
        gridBagConstraints.insets = new java.awt.Insets(4, 4, 4, 4);
        jPanel10.add(Producto_1, gridBagConstraints);

        Producto_3.setText("Producto 3");
        Producto_3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Producto_3MouseClicked(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 0.1;
        gridBagConstraints.weighty = 0.1;
        gridBagConstraints.insets = new java.awt.Insets(4, 4, 4, 4);
        jPanel10.add(Producto_3, gridBagConstraints);

        Producto_4.setText("Producto 4");
        Producto_4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Producto_4MouseClicked(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 0.1;
        gridBagConstraints.weighty = 0.1;
        gridBagConstraints.insets = new java.awt.Insets(4, 4, 4, 4);
        jPanel10.add(Producto_4, gridBagConstraints);

        Producto_2.setText("Producto 2");
        Producto_2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Producto_2MouseClicked(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 0.1;
        gridBagConstraints.weighty = 0.1;
        gridBagConstraints.insets = new java.awt.Insets(4, 4, 4, 4);
        jPanel10.add(Producto_2, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 0.1;
        gridBagConstraints.weighty = 0.2;
        jPanel2.add(jPanel10, gridBagConstraints);

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/redes/carrito.gif"))); // NOI18N
        jLabel1.setAlignmentY(0.0F);
        jLabel1.setMaximumSize(new java.awt.Dimension(401, 401));
        jLabel1.setMinimumSize(new java.awt.Dimension(401, 401));
        jLabel1.setPreferredSize(new java.awt.Dimension(401, 401));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 0.1;
        gridBagConstraints.weighty = 0.1;
        jPanel2.add(jLabel1, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 0.1;
        gridBagConstraints.weighty = 0.1;
        jPanel5.add(jPanel2, gridBagConstraints);

        jPanel7.setBackground(new java.awt.Color(255, 255, 255));
        jPanel7.setLayout(new java.awt.GridBagLayout());

        jPanel8.setBackground(new java.awt.Color(255, 255, 255));
        jPanel8.setLayout(new java.awt.GridBagLayout());

        jScrollPane1.setViewportView(ListaProductos);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 0.1;
        gridBagConstraints.weighty = 0.1;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        jPanel8.add(jScrollPane1, gridBagConstraints);

        Comprar.setText("Finalizar Compra");
        Comprar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ComprarMouseClicked(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.FIRST_LINE_END;
        gridBagConstraints.weightx = 0.1;
        gridBagConstraints.weighty = 0.1;
        jPanel8.add(Comprar, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 0.1;
        gridBagConstraints.weighty = 0.1;
        jPanel7.add(jPanel8, gridBagConstraints);

        jPanel9.setBackground(new java.awt.Color(255, 255, 255));
        jPanel9.setLayout(new java.awt.GridBagLayout());

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/redes/mapa.jpg"))); // NOI18N
        jLabel2.setMaximumSize(new java.awt.Dimension(700, 500));
        jLabel2.setMinimumSize(new java.awt.Dimension(700, 500));
        jLabel2.setPreferredSize(new java.awt.Dimension(700, 500));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 0.1;
        gridBagConstraints.weighty = 0.1;
        jPanel9.add(jLabel2, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.PAGE_START;
        gridBagConstraints.weighty = 0.1;
        jPanel7.add(jPanel9, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 0.1;
        gridBagConstraints.weighty = 0.1;
        jPanel5.add(jPanel7, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_END;
        gridBagConstraints.weightx = 0.3;
        gridBagConstraints.weighty = 0.1;
        jPanel1.add(jPanel5, gridBagConstraints);

        jPanel6.setBackground(new java.awt.Color(255, 255, 255));
        jPanel6.setLayout(new java.awt.GridBagLayout());

        jButton2.setText("Ruta Corta");
        jButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton2MouseClicked(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.ipadx = 3;
        gridBagConstraints.ipady = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.FIRST_LINE_END;
        gridBagConstraints.weightx = 0.1;
        gridBagConstraints.insets = new java.awt.Insets(1, 0, 0, 0);
        jPanel6.add(jButton2, gridBagConstraints);

        jButton3.setText("Cargar Lista");
        jButton3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton3MouseClicked(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.ipadx = 3;
        gridBagConstraints.ipady = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.FIRST_LINE_END;
        gridBagConstraints.weightx = 0.1;
        gridBagConstraints.insets = new java.awt.Insets(1, 0, 0, 0);
        jPanel6.add(jButton3, gridBagConstraints);

        jButton5.setText("Mostrar Ofertas");
        jButton5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton5MouseClicked(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.ipadx = 3;
        gridBagConstraints.ipady = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.FIRST_LINE_END;
        gridBagConstraints.weightx = 0.1;
        gridBagConstraints.weighty = 0.1;
        gridBagConstraints.insets = new java.awt.Insets(1, 0, 0, 0);
        jPanel6.add(jButton5, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.VERTICAL;
        gridBagConstraints.weighty = 0.1;
        jPanel1.add(jPanel6, gridBagConstraints);

        jTabbedPane1.addTab("Supermercado", jPanel1);

        jPanel12.setLayout(new java.awt.GridBagLayout());

        jPanel13.setLayout(new java.awt.GridBagLayout());

        jPanel14.setBackground(new java.awt.Color(255, 255, 255));
        jPanel14.setLayout(new java.awt.GridBagLayout());

        jPanel15.setBackground(new java.awt.Color(255, 255, 255));
        jPanel15.setLayout(new java.awt.GridBagLayout());

        ProductoCasa1.setText("Producto 1");
        ProductoCasa1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ProductoCasa1MouseClicked(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 0.1;
        gridBagConstraints.weighty = 0.1;
        gridBagConstraints.insets = new java.awt.Insets(4, 4, 4, 4);
        jPanel15.add(ProductoCasa1, gridBagConstraints);

        ProductoCasa3.setText("Producto 3");
        ProductoCasa3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ProductoCasa3MouseClicked(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 0.1;
        gridBagConstraints.weighty = 0.1;
        gridBagConstraints.insets = new java.awt.Insets(4, 4, 4, 4);
        jPanel15.add(ProductoCasa3, gridBagConstraints);

        ProductoCasa4.setText("Producto 4");
        ProductoCasa4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ProductoCasa4MouseClicked(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 0.1;
        gridBagConstraints.weighty = 0.1;
        gridBagConstraints.insets = new java.awt.Insets(4, 4, 4, 4);
        jPanel15.add(ProductoCasa4, gridBagConstraints);

        ProductoCasa2.setText("Producto 2");
        ProductoCasa2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ProductoCasa2MouseClicked(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 0.1;
        gridBagConstraints.weighty = 0.1;
        gridBagConstraints.insets = new java.awt.Insets(4, 4, 4, 4);
        jPanel15.add(ProductoCasa2, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 0.1;
        gridBagConstraints.weighty = 0.2;
        jPanel14.add(jPanel15, gridBagConstraints);

        jLabel3.setBackground(new java.awt.Color(255, 255, 255));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/redes/Refrigeradora.gif"))); // NOI18N
        jLabel3.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        jLabel3.setAlignmentY(0.0F);
        jLabel3.setMaximumSize(new java.awt.Dimension(401, 401));
        jLabel3.setMinimumSize(new java.awt.Dimension(401, 401));
        jLabel3.setPreferredSize(new java.awt.Dimension(401, 401));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 0.1;
        gridBagConstraints.weighty = 0.1;
        jPanel14.add(jLabel3, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 0.1;
        gridBagConstraints.weighty = 0.1;
        jPanel13.add(jPanel14, gridBagConstraints);

        jPanel16.setBackground(new java.awt.Color(255, 255, 255));
        jPanel16.setLayout(new java.awt.GridBagLayout());

        jPanel17.setBackground(new java.awt.Color(255, 255, 255));
        jPanel17.setLayout(new java.awt.GridBagLayout());

        jScrollPane2.setViewportView(ListaProductosCasa);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 0.1;
        gridBagConstraints.weighty = 0.1;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        jPanel17.add(jScrollPane2, gridBagConstraints);

        Comprar1.setText("Comprar Lista de Productos");
        Comprar1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Comprar1MouseClicked(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.FIRST_LINE_END;
        gridBagConstraints.weightx = 0.1;
        gridBagConstraints.weighty = 0.1;
        jPanel17.add(Comprar1, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 0.1;
        gridBagConstraints.weighty = 0.1;
        jPanel16.add(jPanel17, gridBagConstraints);

        jPanel18.setBackground(new java.awt.Color(255, 255, 255));
        jPanel18.setLayout(new java.awt.GridBagLayout());
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.PAGE_START;
        gridBagConstraints.weighty = 0.1;
        jPanel16.add(jPanel18, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 0.1;
        gridBagConstraints.weighty = 0.1;
        jPanel13.add(jPanel16, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_END;
        gridBagConstraints.weightx = 0.3;
        gridBagConstraints.weighty = 0.1;
        jPanel12.add(jPanel13, gridBagConstraints);

        jPanel19.setBackground(new java.awt.Color(255, 255, 255));
        jPanel19.setLayout(new java.awt.GridBagLayout());

        jButton8.setText("Generar lista");
        jButton8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton8MouseClicked(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.ipadx = 3;
        gridBagConstraints.ipady = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.FIRST_LINE_END;
        gridBagConstraints.weightx = 0.1;
        gridBagConstraints.insets = new java.awt.Insets(1, 0, 0, 0);
        jPanel19.add(jButton8, gridBagConstraints);

        jButton9.setText("Eliminar");
        jButton9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton9MouseClicked(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.ipadx = 3;
        gridBagConstraints.ipady = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.FIRST_LINE_END;
        gridBagConstraints.weightx = 0.1;
        gridBagConstraints.insets = new java.awt.Insets(1, 0, 0, 0);
        jPanel19.add(jButton9, gridBagConstraints);

        jButton10.setText("Cambiar Supermercado");
        jButton10.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton10MouseClicked(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.ipadx = 3;
        gridBagConstraints.ipady = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.FIRST_LINE_END;
        gridBagConstraints.weightx = 0.1;
        gridBagConstraints.weighty = 0.1;
        gridBagConstraints.insets = new java.awt.Insets(1, 0, 0, 0);
        jPanel19.add(jButton10, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.VERTICAL;
        gridBagConstraints.weighty = 0.1;
        jPanel12.add(jPanel19, gridBagConstraints);

        jTabbedPane1.addTab("Casa", jPanel12);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1525, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 811, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("Restaurante", jPanel3);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1525, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 811, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("Centro Comercial", jPanel4);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Comprar1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Comprar1MouseClicked
        comprarLista(1);
    }//GEN-LAST:event_Comprar1MouseClicked

    private void ProductoCasa2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ProductoCasa2MouseClicked
        Producto p = getProductoInventario("Producto 2");
        p.setCantidadInventario(p.getCantidadInventario() - 1);
        addProducto(p, 1);
    }//GEN-LAST:event_ProductoCasa2MouseClicked

    private void ProductoCasa4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ProductoCasa4MouseClicked
        Producto p = getProductoInventario("Producto 4");
        p.setCantidadInventario(p.getCantidadInventario() - 1);
        addProducto(p, 1);
    }//GEN-LAST:event_ProductoCasa4MouseClicked

    private void ProductoCasa3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ProductoCasa3MouseClicked
        Producto p = getProductoInventario("Producto 3");
        p.setCantidadInventario(p.getCantidadInventario() - 1);
        addProducto(p, 1);
    }//GEN-LAST:event_ProductoCasa3MouseClicked

    private void ProductoCasa1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ProductoCasa1MouseClicked
        Producto p = getProductoInventario("Producto 1");
        p.setCantidadInventario(p.getCantidadInventario() - 1);
        addProducto(p, 1);
    }//GEN-LAST:event_ProductoCasa1MouseClicked

    public JList<Producto> getLista(int tipo) {
        return (tipo == 0) ? ListaProductos : ListaProductosCasa;
    }

    public void actualizarPrecio(String nombre) {
        JButton[] botones = {Producto_1, Producto_2, Producto_3, Producto_4};
        float precio;
        String texto;
        Producto p;
        for (int i = 0; i < 4; i++) {
            texto = botones[i].getText().substring(0, 10);
            if (nombre.equals(texto)) {
                p = getProductoInventario(texto);
                if (p.getCantidadInventario() > 0) {
                    precio = (float) (p.getPrecio() * 1.001);
                    p.setPrecio(precio);
                    botones[i].setText(texto + " - (" + precio + ")");
                } else {
                    botones[i].setText(texto + " - (AGOTADO)");
                    p.setCantidadCarrito(p.getCantidadCarrito() - 1);
                }
            }
        }
    }

    public void comprarLista(int tipo) {
        int total = 0;
        int n;
        DefaultListModel modelo = (DefaultListModel) getLista(tipo).getModel();
        if (modelo.size() != 0) {
            for (int i = 0; i < modelo.size(); i++) {
                total += ((Producto) modelo.elementAt(i)).getPrecio() * ((Producto) modelo.elementAt(i)).getCantidadCarrito();
            }

            if (tipo == 0) {
                Object[] options = {"Comprar con tarjeta",
                    "Encontrar fila mas corta",
                    "Cancelar"};
                n = JOptionPane.showOptionDialog(this,
                        "EL TOTAL DE LA COMPRA ES DE " + total + " COLONES \n DESEA CONTINUAR?",
                        "Finalizar Compra",
                        JOptionPane.YES_NO_CANCEL_OPTION,
                        JOptionPane.QUESTION_MESSAGE,
                        null,
                        options,
                        options[2]);
            } else {
                Object[] options = {"Comprar", "Cancelar"};
                n = JOptionPane.showOptionDialog(this,
                        "EL TOTAL DE LA COMPRA ES DE " + total + " COLONES \n DESEA CONTINUAR?",
                        "Finalizar Compra",
                        JOptionPane.YES_NO_CANCEL_OPTION,
                        JOptionPane.QUESTION_MESSAGE,
                        null,
                        options,
                        options[1]) + 3;
            }
            accionComprar(n);
        }
    }

    private void ComprarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ComprarMouseClicked
        comprarLista(0);
    }//GEN-LAST:event_ComprarMouseClicked

    private void Producto_2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Producto_2MouseClicked
        Producto p = getProductoInventario("Producto 2");
        p.setCantidadInventario(p.getCantidadInventario() - 1);
        addProducto(p, 0);
        actualizarPrecio("Producto 2");
    }//GEN-LAST:event_Producto_2MouseClicked

    private void Producto_4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Producto_4MouseClicked
        Producto p = getProductoInventario("Producto 4");
        p.setCantidadInventario(p.getCantidadInventario() - 1);
        addProducto(p, 0);
        actualizarPrecio("Producto 4");
    }//GEN-LAST:event_Producto_4MouseClicked

    private void Producto_3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Producto_3MouseClicked
        Producto p = getProductoInventario("Producto 3");
        p.setCantidadInventario(p.getCantidadInventario() - 1);
        addProducto(p, 0);
        actualizarPrecio("Producto 3");
    }//GEN-LAST:event_Producto_3MouseClicked

    private void Producto_1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Producto_1MouseClicked
        Producto p = getProductoInventario("Producto 1");
        p.setCantidadInventario(p.getCantidadInventario() - 1);
        addProducto(p, 0);
        actualizarPrecio("Producto 1");
    }//GEN-LAST:event_Producto_1MouseClicked

    public Producto getProductoInventario(String p) {
        Producto tmp = inventario.buscar(p);
        return (tmp != null) ? tmp : null;
    }

    public JLabel getjLabel1() {
        return jLabel1;
    }

    public JLabel getjLabel2() {
        return jLabel2;
    }

    private void jButton2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2MouseClicked
        if (ListaProductos.getModel().getSize() != 0) {
            String iconfilename = getjLabel2().getIcon().toString();
            String fileName = iconfilename.substring(iconfilename.lastIndexOf("/") + 1);
            if ("mapa.jpg".equals(fileName)) {
                getjLabel2().setIcon(new ImageIcon(getClass().getResource("/redes/mapa_1.jpg")));
            } else {
                getjLabel2().setIcon(new ImageIcon(getClass().getResource("/redes/mapa.jpg")));
            }
            this.repaint();
        } else {
            JOptionPane.showMessageDialog(this, "La lista de compras está vacia");
        }
    }//GEN-LAST:event_jButton2MouseClicked

    private void jButton3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton3MouseClicked
        ImageIcon icon = new ImageIcon(getClass().getResource("/redes/loading.gif"));
        JOptionPane.showMessageDialog(
                null,
                "Cargando lista de supermercado desde su hogar",
                "Por favor espere", JOptionPane.INFORMATION_MESSAGE,
                icon);
        for (int i = 0; i < 10; i++) {
            addProducto(getProductoInventario("Producto " + ((int) (Math.random() * 4) + 1)), 0);
        }
    }//GEN-LAST:event_jButton3MouseClicked

    private void jButton10MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton10MouseClicked
        JOptionPane.showInputDialog(
                this,
                "Ingrese su nuevo supermercado de preferencia",
                "Mercado de Preferencia",
                JOptionPane.INFORMATION_MESSAGE);

        JOptionPane.showMessageDialog(this, "Cambio realizado exitosamente", "Proceso completado",
                JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_jButton10MouseClicked

    private void jButton8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton8MouseClicked
        ImageIcon icon = new ImageIcon(getClass().getResource("/redes/loading.gif"));
        JOptionPane.showMessageDialog(
                null,
                "Revisando contenido y generando lista",
                "Por favor espere", JOptionPane.INFORMATION_MESSAGE,
                icon);
        for (int i = 0; i < 10; i++) {
            addProducto(getProductoInventario("Producto " + ((int) (Math.random() * 4) + 1)), 1);
        }
    }//GEN-LAST:event_jButton8MouseClicked

    private void jButton5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton5MouseClicked
        ImageIcon icon = new ImageIcon(getClass().getResource("/redes/oferta.jpg"));
        JOptionPane.showMessageDialog(
                null,
                "Producto " + ((int) (Math.random() * 4) + 1) + " con descuento del 25%",
                "Ofertas del dia",
                JOptionPane.INFORMATION_MESSAGE,
                icon);
    }//GEN-LAST:event_jButton5MouseClicked

    private void jButton9MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton9MouseClicked
        DefaultListModel model = (DefaultListModel) getLista(1).getModel();
        int selectedIndex = getLista(1).getSelectedIndex();
        if (selectedIndex != -1) {
            model.remove(selectedIndex);
        }
    }//GEN-LAST:event_jButton9MouseClicked

    public void addProducto(Producto p, int lista) {
        boolean flag = false;
        DefaultListModel modelo = (DefaultListModel) getLista(lista).getModel();
        if (modelo.size() == 0) {
            modelo.addElement(p);
        } else {
            for (int i = 0; i < modelo.size(); i++) {
                if (p.getId() == ((Producto) modelo.elementAt(i)).getId()) {
                    p.setCantidadCarrito(((Producto) modelo.elementAt(i)).getCantidadCarrito() + 1);
                    modelo.setElementAt(p, i);
                    flag = true;
                    break;
                }
            }
            if (!flag) {
                modelo.addElement(p);
            }
        }
        getLista(lista).setModel(modelo);
    }

    public void accionComprar(int n) {
        switch (n) {
            case 0:
                JOptionPane.showMessageDialog(this, "Compra efectuada exitosamente \n Gracias por su visita!");
                break;
            case 1:
                int c = (int) (Math.random() * 10) + 1;
                int p = (int) (Math.random() * 10) + 1;
                JOptionPane.showMessageDialog(this, "La caja #" + c + " tiene la fila mas corta... \n Con " + p + " persona(s) adelante");
                break;
            case 2:
                break;
            case 3:
                JOptionPane.showMessageDialog(this, "Lista de productos enviada a su supermercado de preferencia \n Retirar compra en 30 minutos");
                break;
        }
    }

    public void init() {
        this.setExtendedState(this.MAXIMIZED_BOTH);
        this.setVisible(true);
    }

    private Inventario inventario;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Comprar;
    private javax.swing.JButton Comprar1;
    private javax.swing.JList<Producto> ListaProductos;
    private javax.swing.JList<Producto> ListaProductosCasa;
    private javax.swing.JButton ProductoCasa1;
    private javax.swing.JButton ProductoCasa2;
    private javax.swing.JButton ProductoCasa3;
    private javax.swing.JButton ProductoCasa4;
    private javax.swing.JButton Producto_1;
    private javax.swing.JButton Producto_2;
    private javax.swing.JButton Producto_3;
    private javax.swing.JButton Producto_4;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton16;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel14;
    private javax.swing.JPanel jPanel15;
    private javax.swing.JPanel jPanel16;
    private javax.swing.JPanel jPanel17;
    private javax.swing.JPanel jPanel18;
    private javax.swing.JPanel jPanel19;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTabbedPane jTabbedPane1;
    // End of variables declaration//GEN-END:variables
}
